name: "ElasticAPM Sourcemap Action"
description: "Publish sourcemaps to APM."
branding:
  icon: 'bar-chart-2'
  color: 'yellow'

inputs:
  apm_node:
    description: 'Elastic APM endpoint'
    required: true
  service_version:
    description: 'The service version used in the RUM Agent'
    required: true
  service_name:
    description: 'The service name used in the RUM Agent'
    required: true
  sourcemap_build_directory:
    description: 'Where sourcemaps are bundled to (not included in bundle_url path)'
    required: true
  sourcemap_pattern:
    description: 'Sourcemap pattern match'
    required: true
    default: "**/*.map"
  bundle_url:
    description: 'Where sourcemaps are deployed to'
    required: true
  token:
    description: 'Your elastic token'
    required: true
    
runs:
  using: 'node12'
  main: 'index.js'
